apiVersion: v1
kind: Service
metadata:
  labels:
    component: mcrouter
  name: mcrouter
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    component: mcrouter
  ports:
    - name: mcrouter
      port: 5000
      protocol: TCP
      targetPort: 5000